### PR TITLE
Remove useless time.sleep calls in AFD unit tests

### PR DESCRIPTION
**Pull request by JordanP**

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/scality-sproxyd-client-tox/11/<h2>Build result: ABORTED</span></h2>[...truncated 15 lines...]Triggering scality-sproxyd-client-tox » py26,centos6-largeTriggering scality-sproxyd-client-tox » py27,ubuntu12-largeTriggering scality-sproxyd-client-tox » pep8,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,centos7-largeConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: centos6-large-e80 is offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: Waiting for next available executor on centos6-largescality-sproxyd-client-tox » py26,centos6-large appears to be cancelledscality-sproxyd-client-tox » py26,centos6-large completed with result ABORTEDscality-sproxyd-client-tox » py27,ubuntu12-large appears to be cancelledscality-sproxyd-client-tox » py27,ubuntu12-large completed with result ABORTEDConfiguration scality-sproxyd-client-tox » pep8,ubuntu14-large is still in the queue: Waiting for next available executor on ubuntu14-largeConfiguration scality-sproxyd-client-tox » pep8,ubuntu14-large is still in the queue: All nodes of label ‘ubuntu14-large’ are offlineConfiguration scality-sproxyd-client-tox » pep8,ubuntu14-large is still in the queue: Waiting for next available executor on ubuntu14-largescality-sproxyd-client-tox » pep8,ubuntu14-large appears to be cancelledscality-sproxyd-client-tox » pep8,ubuntu14-large completed with result ABORTEDConfiguration scality-sproxyd-client-tox » py27,ubuntu14-large is still in the queue: Waiting for next available executor on ubuntu14-largescality-sproxyd-client-tox » py27,ubuntu14-large appears to be cancelledscality-sproxyd-client-tox » py27,ubuntu14-large completed with result ABORTEDscality-sproxyd-client-tox » py27,centos7-large appears to be cancelledscality-sproxyd-client-tox » py27,centos7-large completed with result ABORTEDSetting status of 0be3232f1764a0b4818c9de1d7e45f02ac0cc75b to FAILURE with url https://37.187.159.67:5443/job/scality-sproxyd-client-tox/11/ and message: Merged build finished.
Test FAILed.

**Comment by NicolasT** [comment]
Are you sure this is OK? With this change, I believe the time between 2 `heartbeat` calls is way too low and could introduce numerical stability issues.

**Comment by JordanP** [comment]
I don't know. I ran this 10 times: no error. But it doesn't prove anything...

**Comment by NicolasT** [comment]
I'm a bit worried the test could still pass, but not actually test what it's supposed to (i.e. even if incorrect changes would be made to the AFD implementation, the test would still pass due to the low interval).

**Pull request closed without merging**
