### PR TITLE
Jenkins `tox` job

### PR DESCRIPTION
**Pull request by NicolasT**

### CODE REVIEW

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/scality-sproxyd-client-tox/3/<h2>Build result: ABORTED</span></h2>[...truncated 14 lines...] > git rev-parse refs/remotes/origin/pr/4/merge^{commit} # timeout=10 > git rev-parse refs/remotes/origin/origin/pr/4/merge^{commit} # timeout=10Checking out Revision 5eb1c5544993f2126d68fb9ddbc63b8583ea2005 (refs/remotes/origin/pr/4/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 5eb1c5544993f2126d68fb9ddbc63b8583ea2005First time build. Skipping changelog.Triggering scality-sproxyd-client-tox » py26,ubuntu14-largeTriggering scality-sproxyd-client-tox » py26,centos6-largeTriggering scality-sproxyd-client-tox » py27,ubuntu12-largeTriggering scality-sproxyd-client-tox » pep8,ubuntu14-largeTriggering scality-sproxyd-client-tox » py26,ubuntu12-largeTriggering scality-sproxyd-client-tox » py27,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,centos7-largeTriggering scality-sproxyd-client-tox » py26,centos7-largeTriggering scality-sproxyd-client-tox » py27,centos6-largeConfiguration scality-sproxyd-client-tox » py26,ubuntu14-large is still in the queue: Waiting for next available executor on ubuntu14-largescality-sproxyd-client-tox » py26,ubuntu14-large completed with result FAILUREscality-sproxyd-client-tox » py26,centos6-large completed with result SUCCESSAbortedAborted by Nicolas TrangezCancelled scality-sproxyd-client-tox » py27,ubuntu14-largeCancelled scality-sproxyd-client-tox » py26,ubuntu12-largeInterrupting #3Setting status of 62787a409f131d28b50b240b64bfb37452f179d2 to FAILURE with url https://37.187.159.67:5443/job/scality-sproxyd-client-tox/3/ and message: Merged build finished.
Test FAILed.

**Comment by NicolasT** [comment]
Retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/scality-sproxyd-client-tox/4/<h2>Build result: FAILURE</span></h2>[...truncated 7 lines...] > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/scality-sproxyd-client +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse refs/remotes/origin/pr/4/merge^{commit} # timeout=10 > git rev-parse refs/remotes/origin/origin/pr/4/merge^{commit} # timeout=10Checking out Revision 5eb1c5544993f2126d68fb9ddbc63b8583ea2005 (refs/remotes/origin/pr/4/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 5eb1c5544993f2126d68fb9ddbc63b8583ea2005First time build. Skipping changelog.Triggering scality-sproxyd-client-tox » py26,centos6-largeTriggering scality-sproxyd-client-tox » py27,ubuntu12-largeTriggering scality-sproxyd-client-tox » pep8,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,centos7-largeConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: centos6-large-3ce is offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: centos6-large-654 is offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: Waiting for next available executor on centos6-large-654scality-sproxyd-client-tox » py26,centos6-large completed with result SUCCESSscality-sproxyd-client-tox » py27,ubuntu12-large completed with result FAILUREscality-sproxyd-client-tox » pep8,ubuntu14-large completed with result SUCCESSscality-sproxyd-client-tox » py27,ubuntu14-large completed with result SUCCESSscality-sproxyd-client-tox » py27,centos7-large completed with result SUCCESSSetting status of 62787a409f131d28b50b240b64bfb37452f179d2 to FAILURE with url https://37.187.159.67:5443/job/scality-sproxyd-client-tox/4/ and message: Merged build finished.
Test FAILed.

**Comment by NicolasT** [comment]
Retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/scality-sproxyd-client-tox/6/<h2>Build result: FAILURE</span></h2>[...truncated 5 lines...] > git config remote.origin.url https://github.com/scality/scality-sproxyd-client # timeout=10Fetching upstream changes from https://github.com/scality/scality-sproxyd-client > git --version # timeout=10 > git -c core.askpass=true fetch --tags --progress https://github.com/scality/scality-sproxyd-client +refs/heads/*:refs/remotes/origin/* +refs/pull/*:refs/remotes/origin/pr/* > git rev-parse refs/remotes/origin/pr/4/merge^{commit} # timeout=10 > git rev-parse refs/remotes/origin/origin/pr/4/merge^{commit} # timeout=10Checking out Revision 5eb1c5544993f2126d68fb9ddbc63b8583ea2005 (refs/remotes/origin/pr/4/merge) > git config core.sparsecheckout # timeout=10 > git checkout -f 5eb1c5544993f2126d68fb9ddbc63b8583ea2005 > git rev-list 5eb1c5544993f2126d68fb9ddbc63b8583ea2005 # timeout=10Triggering scality-sproxyd-client-tox » py26,centos6-largeTriggering scality-sproxyd-client-tox » py27,ubuntu12-largeTriggering scality-sproxyd-client-tox » pep8,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,ubuntu14-largeTriggering scality-sproxyd-client-tox » py27,centos7-largeConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: All nodes of label ‘centos6-large’ are offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: centos6-large-567 is offlineConfiguration scality-sproxyd-client-tox » py26,centos6-large is still in the queue: Waiting for next available executor on centos6-large-567scality-sproxyd-client-tox » py26,centos6-large completed with result SUCCESSscality-sproxyd-client-tox » py27,ubuntu12-large completed with result FAILUREscality-sproxyd-client-tox » pep8,ubuntu14-large completed with result SUCCESSscality-sproxyd-client-tox » py27,ubuntu14-large completed with result SUCCESSscality-sproxyd-client-tox » py27,centos7-large completed with result SUCCESSSetting status of 62787a409f131d28b50b240b64bfb37452f179d2 to FAILURE with url https://37.187.159.67:5443/job/scality-sproxyd-client-tox/6/ and message: Merged build finished.
Test FAILed.

**Comment by JordanP** [comment]
Nicolas vs Jenkins : Round 3 !

**Comment by NicolasT** [comment]
They all succeeded at least once, it's only this one job which seems to have trouble cloning... As I said, jobs should clone from the master node, not from the origin. That makes no sense.

Retest this please.

**Comment by scality** [comment]
Refer to this link for build results (access rights to CI server needed): 
https://37.187.159.67:5443/job/scality-sproxyd-client-tox/7/
Test FAILed.

**Comment by NicolasT** [comment]
Success in https://37.187.159.67:5443/job/scality-sproxyd-client-tox/8/ :rage:

**Comment by JordanP** [comment]
LGTM

**Pull request merged**
